name: RT-KeyBindings
version: 0.00_01
abstract: RT KeyBindings Extension
author: Jesse Vincent <jesse@bestpractical.com>
license: perl
distribution_type: module
no_index:
  directory:
    - html
    - inc
generated_by: Module::Install version 0.36
